<?php
/**
 * Auto generated by prado-cli.php on 2010-11-03 10:57:25.
 */
class I_CategoryRecord extends TActiveRecord
{
	const TABLE='I_Category';

	public $I_Category_ID;
	public $IC_Name;

        public $ingredients = array();

        protected static $RELATIONS=array
        (
            'ingredients' => array(self::HAS_MANY,'IngredientRecord'),
        );
 // Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

      
}
?>