<?php
/*
  Module: ImageRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for ImageRecord table
           Auto generated by Pradosoft
*/
class ImageRecord extends TActiveRecord
{
	const TABLE='Image';

	public $Image_ID;
	public $Image;

	public static function finder($className=__CLASS__)
        // Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
	{
		return parent::finder($className);
	}
}
?>