<?php
/*
  Module: IngredientRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for IngredientRecord table
           Auto generated by Pradosoft
*/
class IngredientRecord extends TActiveRecord
{
	const TABLE='Ingredient';

	public $Ingredient_ID;
	public $Ingredient_Name;
	public $I_Category_ID;


	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>