<?php
/*
  Module: ListRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for ListRecord table
           Auto generated by Pradosoft
*/
class ListRecord extends TActiveRecord
{
	const TABLE='List';

	public $List_ID;
	public $User_ID;
	public $L_Name;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
       
}
?>