<?php
/*
  Module: PantryRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for PantryRecord table
           Auto generated by Pradosoft
*/
class PantryRecord extends TActiveRecord
{
	const TABLE='Pantry';

	public $Pantry_ID;
	public $User_ID;
	public $Ingredient_ID;
	public $Amount;
	public $Measure_ID;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>