<?php
/*
  Module: R_CategoryRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for R_CategoryRecord table
           Auto generated by Pradosoft
*/
class R_CategoryRecord extends TActiveRecord
{
	const TABLE='R_Category';

	public $R_Category_ID;
	public $RC_Name;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>