<?php
/*
  Module: Recipe_CategoryRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for Books table
           Auto generated by Recipe_CategoryRecord
*/
class Recipe_CategoryRecord extends TActiveRecord
{
	const TABLE='Recipe_Category';

	public $RC_ID;
	public $Recipe_ID;
	public $R_Category_ID;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>