<?php
/*
  Module: Recipe_CommentRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for Recipe_CommentRecord table
           Auto generated by Pradosoft
*/
class Recipe_CommentRecord extends TActiveRecord
{
	const TABLE='Recipe_Comment';

	public $RCO_ID;
	public $Recipe_ID;
	public $User_ID;
	public $Comment;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>