<?php
/*
  Module: RecipeRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for RecipeRecord table
           Auto generated by Pradosoft
*/
class RecipeRecord extends TActiveRecord
{
	const TABLE='Recipe';

	public $RI_ID;
	public $R_Name;
	public $Prep_Time;
	public $Cook_Time;
	public $Directions;
	public $Author;
	public $Current_Rating;
	public $Rate_Count;
	public $Is_Approved;
        public $ImageUrl;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>