<?php
/*
  Module: Recipe_IngredientRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for Recipe_IngredientRecord table
           Auto generated by Pradosoft
*/
class Recipe_IngredientRecord extends TActiveRecord
{
	const TABLE='Recipe_Ingredient';

	public $RI_ID;
	public $Recipe_ID;
	public $Ingredient_ID;
	public $Amount;
	public $Measure_ID;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>