<?php
/*
  Module: Recipe_ImgRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for Recipe_ImgRecord table
           Auto generated by Pradosoft
*/
class Recipe_ImgRecord extends TActiveRecord
{
	const TABLE='Recipe_Img';

	public $RI_ID;
	public $Recipe_ID;
	public $Image_ID;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>