<?php
/*
  Module: UserRecord.php
  Author Name(s): Nate Priddy
  Date Created: 12/7/2010
  Purpose: DOA object for UserRecord table
           Auto generated by Pradosoft
*/
class UserRecord extends TActiveRecord
{
	const TABLE='User';

	public $USER_ID;
	public $Username;
	public $Email;
	public $Password;
	public $Passwordsalt;
	public $Role;

	public static function finder($className=__CLASS__)
	// Purpose:Used with active directory prado framework
        // Parameters
        //	@param $className: Class to find object from passed in
        // Returns: finder object
        // Side-effects: None
        {
		return parent::finder($className);
	}
}
?>